"""Initial migration.

Revision ID: 278a74d80bd9
Revises: 
Create Date: 2024-08-16 13:36:36.785787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278a74d80bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('some_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('some_model')
    # ### end Alembic commands ###
